export const menuList = [
  {
    'id': 1,
    'name': 'Homepage',
    'description': '',
    'position': 'header',
    'img': '',
    'icon': 'fa-home',
    'path': '/home',
  },
  {
    'id': 2,
    'name': 'Team Organizationnal chart',
    'description': '',
    'position': 'header',
    'img': '',
    'icon': 'fa-sitemap',
    'path': '/organisationnal-chart',
  },
  {
    'id': 3,
    'name': 'Guidelines',
    'description': '',
    'position': 'header',
    'img': '',
    'icon': 'fa-book',
    'path': '/guidelineView',
  },
  {
    'id': 4,
    'name': 'Diagnostic',
    'description': '',
    'position': 'header',
    'img': 'hopital-o',
    'icon': 'fa-hospital-o',
    'path': '/diagnosticView',
  }
  ,
  {
    'id': 5,
    'name': 'Manage Guidelines',
    'description': '',
    'position': 'admin-business',
    'img': '',
    'icon': 'fa-book',
    'path': '/admin/guideline',
  }
  ,
  {
    'id': 6,
    'name': 'Manage Organisationnal Chart',
    'description': '',
    'position': 'admin-business',
    'img': '',
    'icon': 'fa-sitemap',
    'path': '/admin/organisationnal-chart',
  }
  ,
  {
    'id': 7,
    'name': 'Manage Diagnostic',
    'description': '',
    'position': 'admin-business',
    'img': '',
    'icon': 'fa-hospital-o',
    'path': '/admin/diagnostic',
  }
  ,
  {
    'id': 8,
    'name': 'Manage Roles',
    'description': '',
    'position': 'admin-users-and-roles',
    'img': '',
    'icon': 'fa-universal-access',
    'path': '/admin/role',
  }
  ,
  {
    'id': 9,
    'name': 'Manage Users',
    'description': '',
    'position': 'admin-users-and-roles',
    'img': '',
    'icon': 'fa-users',
    'path': '/admin/user',
  }

  ,
  {
    'id': 10,
    'name': 'Back to admin',
    'description': '',
    'position': 'admin-organisational',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin',
  }

  ,
  {
    'id': 11,
    'name': 'Manage Teams',
    'description': '',
    'position': 'admin-organisational',
    'img': '',
    'icon': 'fa-graduation-cap',
    'path': '/admin/organisationnal-chart/team',
  }

  ,
  {
    'id': 12,
    'name': 'Manage Functions',
    'description': '',
    'position': 'admin-organisational',
    'img': '',
    'icon': 'fa-id-card',
    'path': '/admin/organisationnal-chart/function',
  }

  ,
  {
    'id': 13,
    'name': 'Manage Members',
    'description': '',
    'position': 'admin-organisational',
    'img': '',
    'icon': 'fa-users',
    'path': '/admin/organisationnal-chart/member',
  }
  ,
  {
    'id': 14,
    'name': 'Back to admin',
    'description': '',
    'position': 'admin-user',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin',
  }

  ,
  {
    'id': 15,
    'name': 'Manage roles',
    'description': '',
    'position': 'admin-user',
    'img': '',
    'icon': 'fa-universal-access',
    'path': '/admin/role',
  }

  ,
  {
    'id': 16,
    'name': 'Add a user',
    'description': '',
    'position': 'admin-user',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/user/edit',
  }

  ,
  {
    'id': 17,
    'name': 'Back to admin',
    'description': '',
    'position': 'admin-role',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin',
  }
  ,
  {
    'id': 18,
    'name': 'Add a role',
    'description': '',
    'position': 'admin-role',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/role/edit',
  }
  ,
  {
    'id': 19,
    'name': 'Back to admin organisationnal chart',
    'description': '',
    'position': 'admin-team',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/organisationnal-chart',
  }
  ,
  {
    'id': 20,
    'name': 'Add a team',
    'description': '',
    'position': 'admin-team',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/organisationnal-chart/team/edit',
  }
  ,
  {
    'id': 21,
    'name': 'Back to admin organisationnal chart',
    'description': '',
    'position': 'admin-function',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/organisationnal-chart',
  }
  ,
  {
    'id': 22,
    'name': 'Add a function',
    'description': '',
    'position': 'admin-function',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/organisationnal-chart/function/edit',
  }
  ,
  {
    'id': 23,
    'name': 'Back to admin organisationnal chart',
    'description': '',
    'position': 'admin-member',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/organisationnal-chart',
  }
  ,
  {
    'id': 24,
    'name': 'Add a member',
    'description': '',
    'position': 'admin-member',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/organisationnal-chart/member/edit',
  }
  ,
  {
    'id': 25,
    'name': 'Back to list of roles',
    'description': '',
    'position': 'admin-role-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/role',
  }
  ,
  {
    'id': 26,
    'name': 'Back to list of users',
    'description': '',
    'position': 'admin-user-edit',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/user',
  }
  ,
  {
    'id': 27,
    'name': 'Back to list of members',
    'description': '',
    'position': 'admin-member-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/organisationnal-chart/member',
  }
  ,
  {
    'id': 26,
    'name': 'Back to list of teams',
    'description': '',
    'position': 'admin-team-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/organisationnal-chart/team',
  }
  ,
  {
    'id': 26,
    'name': 'Back to list of functions',
    'description': '',
    'position': 'admin-function-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/organisationnal-chart/function',
  }
  ,
  {
    'id': 27,
    'name': 'Back to admin',
    'description': '',
    'position': 'admin-diag',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin',
  }
  ,
  {
    'id': 28,
    'name': 'Manage environnments',
    'description': '',
    'position': 'admin-diag',
    'img': '',
    'icon': 'fa-envira',
    'path': '/admin/diagnostic/environnement',
  }
  ,
  {
    'id': 29,
    'name': 'Manage servers',
    'description': '',
    'position': 'admin-diag',
    'img': '',
    'icon': 'fa-server',
    'path': '/admin/diagnostic/server',
  }
  ,
  {
    'id': 30,
    'name': 'Manage layers',
    'description': '',
    'position': 'admin-diag',
    'img': '',
    'icon': 'fa-eye',
    'path': '/admin/diagnostic/layer',
  }
  ,
  {
    'id': 31,
    'name': 'Manage applications',
    'description': '',
    'position': 'admin-diag',
    'img': '',
    'icon': 'fa-desktop',
    'path': '/admin/diagnostic/application',
  }
  ,
  {
    'id': 32,
    'name': 'Back to admin',
    'description': '',
    'position': 'admin-guideline',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin',
  }
  ,
  {
    'id': 33,
    'name': 'Add a guideline',
    'description': '',
    'position': 'admin-guideline',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/guideline/edit',
  }
  ,
  {
    'id': 34,
    'name': 'Back to guidelines list',
    'description': '',
    'position': 'admin-guideline-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/guideline',
  }
  ,
  {
    'id': 35,
    'name': 'Back to admin',
    'description': '',
    'position': 'admin-environnement',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic',
  }
  ,
  {
    'id': 36,
    'name': 'Add an environnment',
    'description': '',
    'position': 'admin-environnement',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/diagnostic/environnement/edit',
  }
  ,
  {
    'id': 37,
    'name': 'Back to environnments list',
    'description': '',
    'position': 'admin-environnement-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic/environnement',
  },
  {
    'id': 38,
    'name': 'Back to diagnostic admin',
    'description': '',
    'position': 'admin-layer',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic',
  },
  {
    'id': 39,
    'name': 'Add a layer',
    'description': '',
    'position': 'admin-layer',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/diagnostic/layer/edit',
  }
  ,
  {
    'id': 40,
    'name': 'Back to layers list',
    'description': '',
    'position': 'admin-layer-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic/layer',
  }

  ,
  {
    'id': 41,
    'name': 'Back to diagnostic admin',
    'description': '',
    'position': 'admin-server',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic',
  },
  {
    'id': 42,
    'name': 'Add a server',
    'description': '',
    'position': 'admin-server',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/diagnostic/server/edit',
  }
  ,
  {
    'id': 43,
    'name': 'Back to servers list',
    'description': '',
    'position': 'admin-server-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic/server',
  }
  ,
  {
    'id': 44,
    'name': 'Back to diagnostic admin',
    'description': '',
    'position': 'admin-application',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic',
  },
  {
    'id': 45,
    'name': 'Add an application',
    'description': '',
    'position': 'admin-application',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/diagnostic/application/edit',
  }
  ,
  {
    'id': 46,
    'name': 'Back to applications list',
    'description': '',
    'position': 'admin-application-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic/application',
  },
  {
    'id': 47,
    'name': 'Add a diagnostic',
    'description': '',
    'position': 'admin-diag',
    'img': '',
    'icon': 'fa-plus-square',
    'path': '/admin/diagnostic/edit',
  },
  {
    'id': 48,
    'name': 'Back to diagnostics list',
    'description': '',
    'position': 'diagnostic-view',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic',
  },

  {
    'id': 49,
    'name': 'Go to functionnal guidelines',
    'description': '',
    'position': 'guideline-view',
    'img': '',
    'icon': 'fa-backward',
    'path': '/guidelineFonctionnel',
  },

  {
    'id': 50,
    'name': 'Go to technical guidelines',
    'description': '',
    'position': 'guideline-view',
    'img': '',
    'icon': 'fa-backward',
    'path': '/guidelineTechnique',
  },
  {
    'id': 51,
    'name': 'Back to guidelines',
    'description': '',
    'position': 'guideline-Functional',
    'img': '',
    'icon': 'fa-backward',
    'path': '/guidelineView',
  },
  {
    'id': 52,
    'name': 'Back to guidelines',
    'description': '',
    'position': 'guideline-Technique',
    'img': '',
    'icon': 'fa-backward',
    'path': '/guidelineView',
  },
  {
    'id': 53,
    'name': 'Back to home',
    'description': '',
    'position': 'diagnosticView',
    'img': '',
    'icon': 'fa-backward',
    'path': '/home',
  },
  {
    'id': 54,
    'name': 'Back to home',
    'description': '',
    'position': 'organisationnal-chart',
    'img': '',
    'icon': 'fa-backward',
    'path': '/home',
  },
  {
    'id': 55,
    'name': 'Back to home',
    'description': '',
    'position': 'view-guideline',
    'img': '',
    'icon': 'fa-backward',
    'path': '/home',
  },
  {
    'id': 56,
    'name': 'Back to diagnostics list',
    'description': '',
    'position': 'admin-diagnostic-edit',
    'img': '',
    'icon': 'fa-backward',
    'path': '/admin/diagnostic',
  }

];
